language: php
php:
- 5.4
- 5.5
- 5.6
env:
- TEST_MIDDLEWARE=1
- TEST_MIDDLEWARE=0
matrix:
  allow_failures:
  - env: TEST_MIDDLEWARE=1
install:
- sudo apt-get update
- sudo apt-get install php5-dev
- travis_retry composer self-update
- travis_retry composer require satooshi/php-coveralls "^1" --no-update --dev
- travis_retry composer install
before_script:
- php-config || true
- phpenv rehash
- phpenv version-name
- bash tests/travis-setup.sh
script:
- phpunit --testsuite All
  # - '[ $TEST_MIDDLEWARE ] && phpunit --testsuite Middleware'
after_success:
- php vendor/bin/coveralls -v
# - bash tests/run-ext-tests
cache:
  apt: true
  directories:
  - vendor
